[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "../macros" }
bevy = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
ron = { workspace = true }
bevy_elf = { workspace = true }

[build-dependencies]
build = { path = "../build" }
thiserror = "2.0"
